version: '3.0'

services:
  db:
    image: timescale/timescaledb-ha:pg14-latest
    ports:
      - 127.0.0.1:5432:5432/tcp
    volumes:
      - /var/data/timescaledb/:/home/postgres/pgdata/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      TSTUNE_PROFILE: promscale

  promscale:
    image: timescale/promscale:0.16
    ports:
      - 9201:9201/tcp
      - 9202:9202/tcp
    restart: on-failure
    depends_on:
      - db
    volumes:
      - ${PWD}/promscale_prometheus.yml:/prometheus.yml
      - ${PWD}/rules.yml:/rules.yml
      - ${PWD}/alerts.yml:/alerts.yml
    environment:
      PROMSCALE_DB_URI: postgres://postgres:password@db:5432/postgres?sslmode=allow
      PROMSCALE_METRICS_RULES_CONFIG_FILE: /prometheus.yml

  node-exporter:
    image: prom/node-exporter:v1.5.0
    ports:
      - 9100:9100
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100

  prometheus:
    image: prom/prometheus:v2.40.5
    depends_on:
     - promscale
     - node-exporter
    ports:
      - 9090:9090/tcp
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml     

  alertmanager:
    image: prom/alertmanager:v0.24.0
    ports:
      - 9093:9093/tcp

  grafana:
    image: grafana/grafana:9.3.1
    depends_on:
      - promscale
    ports:
      - 3000:3000
    volumes:
      - /var/lib/grafana:/var/lib/grafana
      - /var/log/grafana:/var/log/grafana
      - ${PWD}/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 3000