version: '3.0'

services:
  node-exporter:
    image: prom/node-exporter:v1.6.1
    ports:
      - 9100:9100
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100

  prometheus:
    image: prom/prometheus:v2.47.2
    depends_on:
     - node-exporter
    ports:
      - 9090:9090/tcp
    volumes:
      - /pitimejoule/prometheus/data:/data
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:10.1.2
    ports:
      - 3000:3000
    volumes:
      - /pitimejoule/grafana/lib:/var/lib/grafana
      - /pitimejoule/grafana/log:/var/log/grafana
      - ${PWD}/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 3000
