version: '3.0'

services:
  db:
    image: timescale/timescaledb-ha:pg14-latest
    ports:
      - 127.0.0.1:5432:5432/tcp
    volumes:
      - /var/data/timescaledb/:/home/postgres/pgdata/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      TSTUNE_PROFILE: promscale

  promscale:
    image: timescale/promscale:latest
    ports:
      - 9201:9201/tcp
      - 9202:9202/tcp
    restart: on-failure
    depends_on:
      - db
    volumes:
      - ${PWD}/promscale_prometheus.yml:/prometheus.yml
      - ${PWD}/rules.yml:/rules.yml
      - ${PWD}/alerts.yml:/alerts.yml
    environment:
      PROMSCALE_DB_URI: postgres://postgres:password@db:5432/postgres?sslmode=allow
      PROMSCALE_METRICS_RULES_CONFIG_FILE: /prometheus.yml

