global:
  scrape_interval:     10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: node-exporter
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: promscale
    static_configs:
      - targets: ['promscale:9201']
  - job_name: meteo
    static_configs:
      - targets: ['apisix:9080']
  - job_name: pijoule
    static_configs:
      - targets: ['192.168.1.43:8000']

remote_write:
  - url: "http://promscale:9201/write"
remote_read:
  - url: "http://promscale:9201/read"
    read_recent: true